---
- name: Fetch SSH Keys from Another Machine and Install Locally
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:

    # Step 1: Ensure ~/.ssh directory exists on the current machine
    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    # Step 2: Retrieve private key (id_rsa) from the remote machine
    - name: Fetch id_rsa (private key) from remote machine
      delegate_to: "{{ remote_machine_ip }}"
      become: false
      copy:
        remote_src: yes
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        mode: '0600'

    # Step 3: Retrieve public key (id_rsa.pub) from the remote machine
    - name: Fetch id_rsa.pub (public key) from remote machine
      delegate_to: "{{ remote_machine_ip }}"
      become: false
      copy:
        remote_src: yes
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/id_rsa.pub
        mode: '0644'

    # Step 4: Retrieve authorized_keys from the remote machine
    - name: Fetch authorized_keys from remote machine
      delegate_to: "{{ remote_machine_ip }}"
      become: false
      copy:
        remote_src: yes
        src: ~/.ssh/authorized_keys
        dest: ~/.ssh/authorized_keys
        mode: '0600'

    # Step 5: Notify user that SSH keys have been copied
    - name: Notify user that SSH keys have been copied
      debug:
        msg: "SSH keys and authorized_keys have been copied from {{ remote_machine_ip }} and set up on the current machine."
