---
- name: WSL2 Bootstrap Playbook
  hosts: localhost
  become: yes

  tasks:

    # Update and upgrade the system
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    # Install Python3 and pip
    - name: Install Python3 and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present

    # Install dependencies for Docker
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    # Add Docker GPG key
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Add Docker apt repository
    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    # Install Docker
    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    # Install Docker Python module
    - name: Install Docker Python module
      pip:
        name: docker

    # Start and enable Docker service
    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        enabled: yes
        state: started

    # Add user to Docker group
    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Optional: Verify Docker installation
    - name: Verify Docker is installed
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        var: docker_version.stdout

