---
- name: WSL2 Bootstrap Playbook
  hosts: localhost
  become: true

  vars:
    # Define the essential packages
    essential_packages:
      - curl
      - wget

    # Python installation control
    install_python: true
    python_packages:
      - python3
      - python3-pip
      - python3-venv

    # Docker installation control
    install_docker: true
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  tasks:

    # Step 1: Update and upgrade system packages
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    # Step 2: Install essential packages (curl, wget)
    - name: Install essential packages
      apt:
        name: "{{ essential_packages }}"
        state: present

    # Step 3: Conditionally install Python and related tools
    - name: Install Python packages
      apt:
        name: "{{ python_packages }}"
        state: present
      when: install_python

    # Step 4: Conditionally install Docker and related tools
    - name: Install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present
      when: install_docker
