---
- name: WSL2 Bootstrap Playbook
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:

    # Step 1: Update and upgrade packages
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    # Step 2: Install essential system packages
    - name: Install essential packages
      apt:
        name: "{{ essential_packages }}"
        state: present

    # Step 3: Install Python and related tools
    - name: Install Python packages
      apt:
        name: "{{ python_packages }}"
        state: present
      when: install_python

    # Step 4: Add Docker's official GPG key
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Step 5: Set up Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # Step 6: Install Docker and Docker-related tools
    - name: Install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present
      when: install_docker

    # Step 7: Install Zsh
    - name: Install Zsh packages
      apt:
        name: "{{ zsh_packages }}"
        state: present
      when: install_zsh

    # Step 8: Install additional development tools
    - name: Install development tools
      apt:
        name: "{{ development_packages }}"
        state: present
      when: install_dev_tools
