---
- name: Setup Python, Docker, Terraform, and additional repositories on Ubuntu
  hosts: localhost
  become: yes

  vars:
    repos:
      - repo_url: "https://github.com/zenxedo/terraform.git"
        dest: "/home/{{ ansible_user }}/terraform"
      - repo_url: "https://github.com/zenxedo/ansible"
        dest: "/home/{{ ansible_user }}/ansible"
      # Add more repositories here

  tasks:

    # Update and upgrade the system
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    # Install Python3 and pip
    - name: Install Python3 and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present

    # Install Docker dependencies
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    # Add Docker GPG key
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Add Docker apt repository
    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    # Install Docker
    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    # Install Docker Python module
    - name: Install Docker Python module
      pip:
        name: docker

    # Start and enable Docker service
    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        enabled: yes
        state: started

    # Add current user to Docker group
    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Install HashiCorp GPG key
    - name: Install HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    # Add HashiCorp repository for Terraform
    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    # Install Terraform
    - name: Install Terraform
      apt:
        name: terraform
        state: present

    # Clone additional repositories from the variable list
        # Clone private repositories from the variable list using SSH
    - name: Clone private repositories via SSH
      git:
        repo: "{{ item.repo_url }}"
        dest: "{{ item.dest }}"
        key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"  # Path to your SSH private key
      with_items: "{{ repos }}"


    # Optional: Verify Docker installation
    - name: Verify Docker is installed
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        var: docker_version.stdout

    # Optional: Verify Terraform installation
    - name: Verify Terraform is installed
      command: terraform --version
      register: terraform_version

    - name: Show Terraform version
      debug:
        var: terraform_version.stdout
