---
- name: WSL2 Bootstrap Playbook with Conditional SSH Key Fetching
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:

    # Step 1: Conditionally include the SSH key fetching playbook
    - name: Include SSH key fetching playbook if fetch_ssh_keys is true
      include_playbook: fetch_ssh_keys.yml
      when: fetch_ssh_keys

    # Step 2: Update and upgrade packages
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    # Step 3: Install essential system packages
    - name: Install essential packages
      apt:
        name: "{{ essential_packages }}"
        state: present

    # Step 4: Install Python and related tools
    - name: Install Python packages
      apt:
        name: "{{ python_packages }}"
        state: present
      when: install_python

    # Step 5: Install Docker and Docker-related tools
    - name: Install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present
      when: install_docker

    # Step 6: Install Zsh
    - name: Install Zsh packages
      apt:
        name: "{{ zsh_packages }}"
        state: present
      when: install_zsh

    # Step 7: Install additional development tools
    - name: Install development tools
      apt:
        name: "{{ development_packages }}"
        state: present
      when: install_dev_tools
